# Generated by Django 6.0.7 on 2026-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='driver_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='driver_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], default='rider', max_length=10),
        ),
    ]
