# Generated by Django 6.0.7 on 2026-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customeruser_driver_lat_customeruser_driver_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='total_passengers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='e.g. Sedan, SUV', max_length=50),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
