# Generated by Django 6.0.7 on 2026-07-30 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0002_communitypost_postcomment_ridereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rideorder',
            name='claimed_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats claimed by riders so far'),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='offered_seats',
            field=models.PositiveIntegerField(default=1, help_text='Total seats driver is offering'),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='ride_type',
            field=models.CharField(choices=[('request', 'Request'), ('offer', 'Offer')], default='request', max_length=10),
        ),
        migrations.CreateModel(
            name='RideClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_taken', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ordering_service.rideorder')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ride_order', 'rider')},
            },
        ),
    ]
