# Generated by Django 6.0.7 on 2026-08-05 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0003_rideorder_claimed_seats_rideorder_offered_seats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ordering_service.rideorder')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
