# Generated by Django 6.0.7 on 2026-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
