# Generated by Django 6.0.7 on 2026-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=101)),
                ('destination', models.CharField(max_length=101)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats_available', models.IntegerField()),
            ],
        ),
    ]
